In [14]:
import pandas as pd

In [16]:
Sales = pd.Series([12500, 9800, 15200, 11000, 13400],
index = ["Mon", "Tue", "Wed", "Thus","Fri"])

In [17]:
print(Sales)

Mon     12500
Tue      9800
Wed     15200
Thus    11000
Fri     13400
dtype: int64


2. Print Wednusday Sales....

In [19]:
print("WednusDay Sales : -> ", Sales['Wed'])

WednusDay Sales : ->  15200


3. Print Avarage Of Sales...

In [20]:
print("Avareages = >", Sales.mean())

Avareages = > 12380.0


2. DataFrames

In [21]:
import pandas as pd

In [23]:
employee = pd.DataFrame({
    'Name':["Priya Sharma", "Rahul Verma", "Anita desai"],
    'Department': ["Data Science", "Finance", "HR"],
    'Salary':[800000, 850000, 90000]
})

In [24]:
print(employee)

           Name    Department  Salary
0  Priya Sharma  Data Science  800000
1   Rahul Verma       Finance  850000
2   Anita desai            HR   90000


Shape

In [26]:
print("Shape: ->", employee.shape)

Shape: -> (3, 3)


3.

In [27]:
import pandas as pd

In [ ]:
import pandas as pd

# Step 1: create a small CSV file (as if exported from NeoMart billing)
csv_text = """order_id,customer,city,amount
101,Priya Sharma,Mumbai,2499.0
102,Rahul Verma,Delhi,1250.5
103,Anita Desai,Pune,3999.0
104,Priya Sharma,Mumbai,799.0
"""

In [36]:
with open("orders.csv", "w") as f:
    f.write(csv_text)

# Step 2: read it back into a DataFrame
orders = pd.read_csv("orders.csv")
print(orders.head())
print("Rows and columns:", orders.shape)

   order_id      customer    city  amount
0       101  Priya Sharma  Mumbai  2499.0
1       102   Rahul Verma   Delhi  1250.5
2       103   Anita Desai    Pune  3999.0
3       104  Priya Sharma  Mumbai   799.0
Rows and columns: (4, 4)


4.

In [42]:
import pandas as pd

orders = pd.DataFrame({
    "order_id": [101, 103, 103],
    "Customers": ["Priya sharma", "Rahul verma", "Anita desai"],
    "Amount": [1299.00, 1599.00, 1999.00]
})
orders.to_excel("orders.xlsx", index=False) ## convert file into excel
from_excel = pd.read_excel("orders.xlsx") ## read the excel file
print(from_excel)


   order_id     Customers  Amount
0       101  Priya sharma    1299
1       103   Rahul verma    1599
2       103   Anita desai    1999


5.First health check: info and describe

In [44]:
import pandas as pd
orders = pd.DataFrame({
    "order_id":[101, 102, 103, 104],
     "customer": ["Priya Sharma", "Rahul Verma", "Anita Desai", "Priya Sharma"],
     "city" : ["Mumbai", "Delhi", "Pune", "Mumbai"],
     "amount": [2499.0, 1250.5, 3999.0, 799.0]
})
print(orders.info())
print(orders.describe())

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   order_id  4 non-null      int64  
 1   customer  4 non-null      str    
 2   city      4 non-null      str    
 3   amount    4 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 260.0 bytes
None
         order_id       amount
count    4.000000     4.000000
mean   102.500000  2136.875000
std      1.290994  1434.597991
min    101.000000   799.000000
25%    101.750000  1137.625000
50%    102.500000  1874.750000
75%    103.250000  2874.000000
max    104.000000  3999.000000


1.Create a Series of patient counts at MediCare Clinic for Mon–Thu: 32, 41, 28, 35. Print it and print the busiest day count using .max().

In [45]:
import pandas as pd

patients = pd.Series([32, 41, 28, 35],
                     index=["Mon", "Tue", "Wed", "Thu"])
print(patients)
print("Busient day count", patients.max())


Mon    32
Tue    41
Wed    28
Thu    35
dtype: int64
Busient day count 41


2.Build a DataFrame of 3 NeoMart products (product, price) and print head() and shape.

In [46]:
products = pd.DataFrame({
   'Product': ['salt 2kg', 'sugar 5kg', 'Oil 2ltr'],
   'Price' : [90.0, 50.0, 80.0]})
print(products.head())
print("Shape  => ",products.shape)


     Product  Price
0   salt 2kg   90.0
1  sugar 5kg   50.0
2   Oil 2ltr   80.0
Shape  =>  (3, 2)


Selecting Colums

In [47]:
import pandas as pd

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105],
    "customer": ["Priya Sharma", "Rahul Verma", "Anita Desai",
                 "Priya Sharma", "Rahul Verma"],
    "city": ["Mumbai", "Delhi", "Pune", "Mumbai", "Delhi"],
    "amount": [2499.0, 1250.5, 3999.0, 799.0, 5400.0]
})

In [ ]:
print(orders['amount']) ## print single values
print(orders[['amount', 'customer']]) ### print multiple values

0    2499.0
1    1250.5
2    3999.0
3     799.0
4    5400.0
Name: amount, dtype: float64
   amount      customer
0  2499.0  Priya Sharma
1  1250.5   Rahul Verma
2  3999.0   Anita Desai
3   799.0  Priya Sharma
4  5400.0   Rahul Verma


## Selecting rows: loc vs iloc

In [55]:
import pandas as pd

orders = pd.DataFrame(
    {"customer": ["Priya Sharma", "Rahul Verma", "Anita Desai"],
     "amount": [2499.0, 1250.5, 3999.0]},
    index=["ord101", "ord102", "ord103"])
print(orders.loc['ord102']) # by label
print(orders.iloc[0])  ## print by Position
print(orders.loc['ord101', 'amount'])
print(orders.iloc[0:2])

customer    Rahul Verma
amount           1250.5
Name: ord102, dtype: object
customer    Priya Sharma
amount            2499.0
Name: ord101, dtype: object
2499.0
            customer  amount
ord101  Priya Sharma  2499.0
ord102   Rahul Verma  1250.5


## Filtering with conditions

In [57]:
import pandas as pd

txns = pd.DataFrame({
    "txn_id": [1, 2, 3, 4, 5],
    "customer": ["Priya", "Rahul", "Anita", "Priya", "Rahul"],
    "type": ["debit", "credit", "debit", "debit", "credit"],
    "amount": [1200.0, 50000.0, 349.0, 15000.0, 2000.0]
})
big = txns[txns["amount"] > 10000]
print(big)
big_debits = txns[(txns["amount"] > 1000) & (txns["type"] == "debit")]
print(big_debits)

   txn_id customer    type   amount
1       2    Rahul  credit  50000.0
3       4    Priya   debit  15000.0
   txn_id customer   type   amount
0       1    Priya  debit   1200.0
3       4    Priya  debit  15000.0


Sorting

In [58]:
import pandas as pd
txns = pd.DataFrame({
    "customer": ["Priya", "Rahul", "Anita", "Priya"],
    "amount": [1200.0, 50000.0, 349.0, 15000.0]
})
print(txns.sort_values("amount", ascending=False))
print(txns.sort_values(["customer", "amount"]))

  customer   amount
1    Rahul  50000.0
3    Priya  15000.0
0    Priya   1200.0
2    Anita    349.0
  customer   amount
2    Anita    349.0
0    Priya   1200.0
3    Priya  15000.0
1    Rahul  50000.0


In [59]:
import pandas as pd

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105],
    "city": ["Mumbai", "Delhi", "Pune", "Mumbai", "Mumbai"],
    "amount": [2499.0, 1250.5, 3999.0, 799.0, 5400.0]
})
mumbai_great = orders[(orders["city"] == "Mumbai") & (orders["amount"] > 1000)]
print(mumbai_great.sort_values('amount', ascending=False))
print("Mumbai Revenue ->", mumbai_great["amount"].sum())

   order_id    city  amount
4       105  Mumbai  5400.0
0       101  Mumbai  2499.0
Mumbai Revenue -> 7899.0


Columns, Type Conversion, Strings and Dates

In [71]:
emp = pd.DataFrame({
    "name": ["Priya Sharma", "Rahul Verma", "Anita Desai"],
    "salary": [85000, 62000, 58000]
})
emp['salary'] = emp['salary'] + 3000
emp["bonus"] = emp['salary'] * 0.10
emp["company"] = 'TechCorp'
print(emp)
emp = emp.drop(columns=["company"])          # delete a column
print(emp)

           name  salary   bonus   company
0  Priya Sharma   88000  8800.0  TechCorp
1   Rahul Verma   65000  6500.0  TechCorp
2   Anita Desai   61000  6100.0  TechCorp
           name  salary   bonus
0  Priya Sharma   88000  8800.0
1   Rahul Verma   65000  6500.0
2   Anita Desai   61000  6100.0


Converting types with astype

In [76]:
import pandas as pd

orders = pd.DataFrame({
    "order_id": ["101", "102", "103"],
    "amount": ["2499.50", "1250.00", "3999.90"]
})
print(orders.dtypes) ## Data types
orders["order_id"] = orders["order_id"].astype(int)
orders["amount"] = orders["amount"].astype(float)
print(orders.dtypes)
print("Total", orders["amount"].sum())


order_id    str
amount      str
dtype: object
order_id      int64
amount      float64
dtype: object
Total 7749.4


In [79]:
import pandas as pd

cust = pd.DataFrame({
    "name": ["  priya sharma", "RAHUL VERMA  ", "anita desai"],
    "email": ["priya@neomart.in", "rahul@gmail.com", "anita@neomart.in"]
})
cust['name'] = cust['name'].str.strip().str.title()
cust["is_staff"] = cust["email"].str.contains("neomart")
print(cust)

           name             email  is_staff
0  Priya Sharma  priya@neomart.in      True
1   Rahul Verma   rahul@gmail.com     False
2   Anita Desai  anita@neomart.in      True


Dates: pd.to_datetime and .dt

In [81]:
import pandas as pd

txns = pd.DataFrame({
    "txn_id": [1, 2, 3],
    "txn_date": ["2026-08-01", "2026-08-05", "2026-08-10"],
    "amount": [1200.0, 5000.0, 349.0]
})
txns["txn_date"] = pd.to_datetime(txns["txn_date"])
txns["month"] = txns["txn_date"].dt.month
txns["weekday"] = txns["txn_date"].dt.day_name()
print(txns)

   txn_id   txn_date  amount  month    weekday
0       1 2026-08-01  1200.0      8   Saturday
1       2 2026-08-05  5000.0      8  Wednesday
2       3 2026-08-10   349.0      8     Monday


In [84]:
import pandas as pd

survey = pd.DataFrame({
    "customer": ["Priya", "Rahul", None, "Anita"],
    "age": [28, None, 35, 41],
    "rating": [5, 4, None, 3]
})
print(survey)
print(survey.isna()) # True marks a missing cell
print(survey.isna().sum())      # missing count per column

  customer   age  rating
0    Priya  28.0     5.0
1    Rahul   NaN     4.0
2      NaN  35.0     NaN
3    Anita  41.0     3.0
   customer    age  rating
0     False  False   False
1     False   True   False
2      True  False    True
3     False  False   False
customer    1
age         1
rating      1
dtype: int64


Fixing: fillna and dropna

In [91]:
import pandas as pd

survey = pd.DataFrame({
    "customer": ["Priya", "Rahul", None, "Anita"],
    "age": [28, None, 35, 41],
    "rating": [5, 4, None, 3]
})
survey['age'] = survey['age'].fillna(survey['age'].mean())
survey["rating"] = survey["rating"].fillna(0)
print(survey)
survey = survey.dropna(subset=["customer"])
print(survey)

  customer        age  rating
0    Priya  28.000000     5.0
1    Rahul  34.666667     4.0
2      NaN  35.000000     0.0
3    Anita  41.000000     3.0
  customer        age  rating
0    Priya  28.000000     5.0
1    Rahul  34.666667     4.0
3    Anita  41.000000     3.0


Duplicates: duplicated and drop_duplicates


In [94]:
import pandas as pd

orders = pd.DataFrame({
    "order_id": [101, 102, 102, 103],
    "customer": ["Priya", "Rahul", "Rahul", "Anita"],
    "amount": [2499.0, 1250.5, 1250.5, 3999.0]
})
print(orders.duplicated())
clean = orders.drop_duplicates()
print(clean)
print("Before:", len(orders), "rows | After:", len(clean), "rows")

0    False
1    False
2     True
3    False
dtype: bool
   order_id customer  amount
0       101    Priya  2499.0
1       102    Rahul  1250.5
3       103    Anita  3999.0
Before: 4 rows | After: 3 rows


apply, map and groupby

In [95]:
import pandas as pd

emp = pd.DataFrame({
    "name": ["Priya Sharma", "Rahul Verma", "Anita Desai"],
    "dept_code": ["DS", "FIN", "HR"],
    "salary": [88000, 65000, 61000]
})
# map: replace codes using a dictionary (a lookup table)
dept_names = {"DS": "Data Science", "FIN": "Finance", "HR": "Human Resources"}
emp["department"] = emp["dept_code"].map(dept_names)
# apply: run a custom function on every value of a column
def tax_slab(salary):
    return "high" if salary > 70000 else "standard"

emp["tax_slab"] = emp["salary"].apply(tax_slab)
print(emp[["name", "department", "tax_slab"]])

           name       department  tax_slab
0  Priya Sharma     Data Science      high
1   Rahul Verma          Finance  standard
2   Anita Desai  Human Resources  standard


2.groupby: split, apply, combine

In [96]:
import pandas as pd

orders = pd.DataFrame({
    "city": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi", "Mumbai"],
    "amount": [2499.0, 1250.5, 799.0, 3999.0, 5400.0, 1500.0]
})
print(orders.groupby('city')['amount'].sum())

city
Delhi     6650.5
Mumbai    4798.0
Pune      3999.0
Name: amount, dtype: float64


3. several aggregations at once

In [100]:
import pandas as pd

orders = pd.DataFrame({
    "city": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi", "Mumbai"],
    "amount": [2499.0, 1250.5, 799.0, 3999.0, 5400.0, 1500.0]
})
reports = orders.groupby('city')['amount'].agg(['count', 'sum', 'mean'])
print(reports)

report2 = orders.groupby("city").agg(
    total_sales=("amount", "sum"),
    biggest_order=("amount", "max")
)
print(report2)

        count     sum         mean
city                              
Delhi       2  6650.5  3325.250000
Mumbai      3  4798.0  1599.333333
Pune        1  3999.0  3999.000000
        total_sales  biggest_order
city                              
Delhi        6650.5         5400.0
Mumbai       4798.0         2499.0
Pune         3999.0         3999.0


SafeBank: branches ["Andheri", "Karol Bagh", "Andheri", "Karol Bagh"], types ["debit", "credit", "debit", "debit"], amounts [1200.0, 50000.0, 349.0, 15000.0]. Add a fee column using apply with a lambda (Day 15): 10.0 if amount > 10000 else 0.0. Then print count and sum of amount per branch.

In [101]:
import pandas as pd

txns = pd.DataFrame({
    "branch": ["Andheri", "Karol Bagh", "Andheri", "Karol Bagh"],
    "type": ["debit", "credit", "debit", "debit"],
    "amount": [1200.0, 50000.0, 349.0, 15000.0]
})
txns['fee'] = txns['amount'].apply(lambda a: 10.0 if a > 1000 else 0.0)
print(txns.groupby("branch")["amount"].agg(["count", "sum"])) 

            count      sum
branch                    
Andheri         2   1549.0
Karol Bagh      2  65000.0


In [104]:
import pandas as pd

customers = pd.DataFrame({
    "cust_id": [1, 2, 3],
    "name": ["Priya Sharma", "Rahul Verma", "Anita Desai"],
    "city": ["Mumbai", "Delhi", "Pune"]
})
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "cust_id": [1, 2, 1, 4],
    "amount": [2499.0, 1250.5, 799.0, 999.0]
})

inner = pd.merge(orders, customers, on='cust_id')
print(inner)

   order_id  cust_id  amount          name    city
0       101        1  2499.0  Priya Sharma  Mumbai
1       102        2  1250.5   Rahul Verma   Delhi
2       103        1   799.0  Priya Sharma  Mumbai


Left merge: keep every order

In [ ]:
import pandas as pd

customers = pd.DataFrame({
    "cust_id": [1, 2, 3],
    "name": ["Priya Sharma", "Rahul Verma", "Anita Desai"]
})
orders = pd.DataFrame({
    "order_id": [101, 102, 104],
    "cust_id": [1, 2, 4],
    "amount": [2499.0, 1250.5, 999.0]
})

left = pd.merge(orders, customers, on='cust_id', how='left')
print(left)

   order_id  cust_id  amount          name
0       101        1  2499.0  Priya Sharma
1       102        2  1250.5   Rahul Verma
2       104        4   999.0           NaN


join: merge by index

In [ ]:
# join lines up rows by INDEX (here: employee names)
salaries = pd.DataFrame({"salary": [88000, 65000]},
                        index=["Priya", "Rahul"])
depts = pd.DataFrame({"dept": ["Data Science", "Finance"]},
                     index=["Priya", "Rahul"])
print(salaries.join(depts))

3. join: merge by index